services:
  user-service:
    build: ./user-service
    ports:
      - "4000:4000"
  password-service:
    build: ./password-service
    ports:
      - "4001:4001"
  frontend:
    build: ./app
    ports:
      - "3000:3000"
  api-gateway:
    build: ./api-gateway
    ports:
      - "3001:3001"