@startuml MVC_class_diagram
!define RECTANGLE class
left to right direction

class PasswordModel {
  -email: str
  -table: DynamoDB.Table
  -encryption_service: EncryptionService
  +add_password(password_name: str, password: str): void
  +get_password(password_name: str): dict
  +get_passwords(): list
  +update_password(password_name: str, new_password: str): void
  +delete_password(password_name: str): void
  +check_password(email: str, password_name: str): bool
}

class EncryptionService {
  -key: bytes
  +encrypt(password: str): dict
  +decrypt(encrypted_data: dict): str
}

class PasswordStrategy {
  +generate_password(): str
}

class EightCharPassword {
  +generate_password(): str
}

class TwelveCharPassword {
  +generate_password(): str
}

class SixteenCharPassword {
  +generate_password(): str
}

class PasswordGenerator {
  -_strategy: PasswordStrategy
  +set_strategy(strategy: PasswordStrategy): void
  +generate(): str
}

PasswordModel --> EncryptionService : Uses
PasswordGenerator --> PasswordStrategy : Uses
PasswordGenerator "1" --> "*" PasswordStrategy : Implements
EightCharPassword --> PasswordStrategy : Implements
TwelveCharPassword --> PasswordStrategy : Implements
SixteenCharPassword --> PasswordStrategy : Implements

@enduml
