name: CI Pipeline with Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest with coverage
        run: |
          pytest --cov=your_module --cov-report=xml

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Run Jest with coverage
        run: |
          npm run test -- --coverage --coverageReporters=clover

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: henry-0810
          token: ${{ secrets.SONAR_TOKEN }}
          projectKey: Henry-0810_Keep-Safe
          projectName: Keep-Safe
